### ISSUE TITLE
2.b.iii Method Selection and Planning Changes

### ISSUE THREAD

**Issue by apj520** [apj520/ENG1-Team-13-Assessment-2#9]

**Comment by apj520** [comment]
Changes to the method selection and planning documentation to fit Assessment 2

**Comment by YumisZyutyu** [comment]
22/04/22 - 10:40

The document is being changed by Brandon - Architecture part, Adam - Website part, Ayman - Implementation part and Yumis - the rest.

**Comment by YumisZyutyu** [comment]
01/05/22 
This document is ready for review, however, a few things are still unclear and thus missing.

- Tools for testing, awaiting Adam.
- The use of photoshop for the Diagrams from plantuml, awaiting Ayman. 
- The quality control measure for the implementation (do you need someone to approve before you commit a change?)
- As well as the final Gantt Chart is not being posted due to the fact we haven't reached the final part of the project yet. 

@westie1138 When reviewing this document, please review it simultaneously with the Method Selection WITH CHANGES file as they are both connected and have undergone changes.

**Comment by westie1138** [comment]
## 03/05/22 - 22:25
Review complete, only minor grammar changes and wording edits made. Assuming the missing elements from above have been implemented, this document is ready for submission.
